simplesocial/accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns=[
    path('login',auth_views.LoginView.as_view(template_name='accounts\login.html'),name="login"),
    path('logout',auth_views.LogoutView.as_view(),name='logout'),
    path('signup',views.SignUp.as_view(),name='signup'),
    
]

simplesocial/groups/urls.py
from django.urls import path
from django.conf.urls import include,url
from . import views

app_name='groups'

urlpatterns=[
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),


]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),


]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>
  <body>

    <nav class='navbar mynav' role='navigation' id='navbar'>
      <div class="container">
        <a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
          <ul class="navbar-link">
            {% if user.is_authenticated %}
              <li> <a href="#">Post</a> </li>
              <li> <a href="#">Groups</a> </li>
              <li> <a href="#">Create Groups</a> </li>
              <li> <a href="{% url 'accounts:logout' %}">Log Out</a> </li>

            {% else %}
              <li> <a href="#">Groups</a> </li>
              <li> <a href="{% url 'accounts:login' %}">Login</a> </li>
              <li> <a href="{% url 'accounts:signup' %}">Sign Up</a> </li>

            {% endif %}
          </ul>



      </div>

    </nav>


<div class="container mycontent">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome to Star Social!!</h1>
{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now Logged In</h1>


{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for Visiting</h1>


{% endblock %}